name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: harikrishnancj
          outputs: dist/snake.svg

      - name: Post-process SVG for dark theme
        run: |
          # Modify colors in the SVG file for dark mode
          sed -i 's/#FFFFFF/#FF5733/g' dist/snake.svg  # Change snake color (example: orange snake)
          sed -i 's/#000000/#121212/g' dist/snake.svg  # Change background to dark (dark theme)
          sed -i 's/#000000/#FFFFFF/g' dist/snake.svg  # Change text color to white for visibility

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
