name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Generate Snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: harikrishnancj
          outputs: |
            ./output/snake.svg
            ./output/snake-dark.svg?palette=github-dark

      - name: Push the files
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate Snake animation"
          add: "output/snake*.svg"
