name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Generate snake.svg with dark theme
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: harikrishnancj
          outputs: dist/snake.svg
          # Correctly customize color parameters
          snake_color: "#FF5733"   # Orange snake color
          bgcolor: "#121212"       # Dark background (dark theme)
          font_color: "#FFFFFF"    # White text for visibility

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
